/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramirezbrianproject3;

import javax.swing.JOptionPane;

/**
 *
 * @author brianramirez
 */
public class PurchaseFrame extends javax.swing.JFrame {
    
    private BookStore myMode1;
    private Product myMode2;
    private Members myMode3;
    private PremiumMembers myMode4;
    
    private boolean enteredName;
    private boolean enteredMember;
    private boolean cartButton;
    private boolean Member;
    /**
     * Creates new form PurchaseFrame
     */
    public PurchaseFrame() {
        initComponents();
    }
    
    PurchaseFrame(BookStore myMode1, Product myMode2, Members myMode3, PremiumMembers myMode4) {
     this.myMode1 = myMode1;
     this.myMode2 = myMode2;
     this.myMode3 = myMode3;
     this.myMode4 = myMode4;
     initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeText = new javax.swing.JTextField();
        AddCartButton = new javax.swing.JButton();
        MemberBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        NameText = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeText.setText("Welcome to the BookStore! Please select from the list of Products below.");
        WelcomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeTextActionPerformed(evt);
            }
        });

        AddCartButton.setText("Add to Cart");
        AddCartButton.setEnabled(false);
        AddCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCartButtonActionPerformed(evt);
            }
        });

        MemberBox.setText("Member? (Check Box)");
        MemberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberBoxActionPerformed(evt);
            }
        });

        ProductList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Farenheit 451 by Ray Bradbury 9.99 (BOOK)", "1984 by George Orwell 15.99 (BOOK)", "To kill a mockingbird by Harper Lee 12.99 (BOOK)", "Beloved by Toni Morrison 12.99 (BOOK)", "The little prince by Antoine de Saint Exupéry 7.00 (BOOK)", "Brave new world by Aldous Huxley 19.00 (BOOK)", "Charlotte's web by E.B White 8.99 (BOOK)", "Hitchhiker's guide to the galaxy by Douglas Adams 9.99 (BOOK)", "Catch-22 by Joseph Heller 11.99 (BOOK)", "Flowers for algernon by Daniel Keyes 6.99 (BOOK)", "A night at the opera by Queen 6.99 (CD)", "A hard day's night by The Beatles 3.99 (CD)", "The dark knight by N/A 12.99 (DVD)", "Jurassic Park by N/A 7.99 (DVD)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ProductList);

        NameText.setText("Enter Name:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WelcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MemberBox)
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddCartButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(AddCartButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void WelcomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WelcomeTextActionPerformed

    private void AddCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCartButtonActionPerformed
        // TODO add your handling code here:
       String s = ProductList.getSelectedValuesList().toString();
       myMode2.setProductName(s);
     // myMode2.setProductName(ProductList.getSelectedValues().toString());
      myMode3.setFirstName(nameField.getText());
     
      EndFrame myEndFrame = new EndFrame(myMode1, myMode2, myMode3, myMode4);
      myEndFrame.setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_AddCartButtonActionPerformed

    private void MemberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberBoxActionPerformed
        // TODO add your handling code here:
       enteredMember = false;
       
       if (MemberBox.isSelected()) {
           enteredMember = true; 
           
           
       }
        
        
    }//GEN-LAST:event_MemberBoxActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        enteredName = true;
        
        if (enteredName) {
        AddCartButton.setEnabled(true);
        
        }
          
    }//GEN-LAST:event_nameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCartButton;
    private javax.swing.JCheckBox MemberBox;
    private javax.swing.JLabel NameText;
    private javax.swing.JList<String> ProductList;
    private javax.swing.JTextField WelcomeText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}

