/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brianproject3;

/**
 *
 * @author brian
 */
public class SummaryFrame extends javax.swing.JFrame {
    
    private BookStore myMode1;
    private Product myMode2;
    private Members myMode3;
    private PremiumMembers myMode4;
    
    /**
     * Creates new form SummaryFrame
     */
    public SummaryFrame() {
        initComponents();
    }
    
    SummaryFrame(BookStore mode1, Product myMode2, Members myMode3, PremiumMembers myMode4) {
     initComponents();
     this.myMode1 = mode1;
     this.myMode2 = myMode2;
     this.myMode3 = myMode3;   
     this.myMode4 = myMode4;
     
     ProductLabel.setText("You have chosen the product: " + myMode2.getProductName()+ ".");
     MemberLabel.setText("Member's Name: " + myMode3.getFirstName());
     PaymentLabel.setText("Method of Payment: " + myMode3.getPaymentMethod());
     MemberID.setText("Member's ID: " + myMode3.getId());
     
     if (myMode4.isFeePaid()== true){
      PremiumPayed.setText("Thank you for paying on time. Fees due on the 29th of each month!");    
     } else {
      PremiumPayed.setText("Remember, Fees due on the 29th of each month! There is a $25 late fee!");    
         
      }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ProductLabel = new javax.swing.JLabel();
        MemberLabel = new javax.swing.JLabel();
        PaymentLabel = new javax.swing.JLabel();
        MemberID = new javax.swing.JLabel();
        PremiumPayed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("****Order Summary!****");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Purchase Again");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ProductLabel.setText("Product Ordered & Amount:");

        MemberLabel.setText("Member's Name: ");

        PaymentLabel.setText("Payment Method: ");

        MemberID.setText("Member's ID:");

        PremiumPayed.setText("Premium:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PaymentLabel)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PremiumPayed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProductLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberLabel)
                    .addComponent(MemberID))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ProductLabel)
                .addGap(18, 18, 18)
                .addComponent(PaymentLabel)
                .addGap(30, 30, 30)
                .addComponent(MemberLabel)
                .addGap(18, 18, 18)
                .addComponent(PremiumPayed)
                .addGap(26, 26, 26)
                .addComponent(MemberID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PurchaseFrame myPurchaseFrame = new PurchaseFrame(myMode1, myMode2, myMode3, myMode4);
        myPurchaseFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel MemberID;
    private javax.swing.JLabel MemberLabel;
    private javax.swing.JLabel PaymentLabel;
    private javax.swing.JLabel PremiumPayed;
    private javax.swing.JLabel ProductLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
